### ISSUE TITLE
Newly digitized items not getting parent_id of EAD (or collection xml)

### ISSUE THREAD

**Issue by jlderidder** [AcumenProject/acumen-indexer#1]

**Comment by 8bitsquid** [comment]
It seems something is going awry, but it may take a little more looking to find it. All rows in the `file` database table should have a `parent_id >= 0`. And something is **really** wrong if the rows with `parent_id = ""` have `found = 1` (anything `found = 0` is considered removed, but kept in the database as a temporary measure).

 The query you mentioned should get the parent id - if you look at the [getParentID()](https://github.com/AcumenProject/acumen-indexer/blob/master/src/main/java/edu/ua/lib/acumen/database/MetadataDAO.java#L186) function, you'll notice the `repoLoc` is "stepped back" by `Location.stepBackLoc()` function, which gets the potential parent repoLoc (e.g., `u0003_0000001` is "stepped" back to `u0003`).

Looking at it now, it is a bit confusing. The `METADATA_GET_PARENT_ID` query assumes you'll always be using a potential parent repoLoc; derived from the current repoLoc by stepping back through the `_` repoLoc delimiter. The `repoLoc` is used instead of `id` because parent items are indexed first, so the `parent_id` value of a an updated item may not be accurate. I probably should have just used a generic `METADATA_GET_ID` when retrieving the `id` for both current items and parent items.

That query should also get the proper XML file, determined by the `status_type_id=1`. This status_type_id was inherited from the legacy Acumen - it's assigned using the `priority` value associated with XML types in the `file_type` table. The highest priority file type is given the status of `1` (meaning it's "released"). If I'm looking at the [inferStatusTypeId()](https://github.com/AcumenProject/acumen-indexer/blob/master/src/main/java/edu/ua/lib/acumen/database/MetadataDAO.java#L269) function right, it should behave properly if higher priority metadata are added with preexisting lower priority ones.

There is something going on from the sound of it, but the issue may lie elsewhere.

**Comment by jlderidder** [comment]
One collection of digitized had no parent ID;  11 collections of digitized
items had parent ID values where the database entry was empty.  Here's the
corrections I made with the date of uploads:

u0003_0003760  -- update parent id from 110931 to 150802  (5/4/2016)
u0003_0003724  -- update parent id from 110720 to 150801  (5/2/2016)
u0003_0002508  -- update parent id from 108179 to 150799  (5/4/2016)
u0003_0001583  -- update parent ID from 101942 to 150797 (6/24-7/13/2016)
u0003_0000630  -- update parent ID from "" to 150792 (5/16/2016)
u0003_0000374   -- update parent ID from 48873 to 150790 (6/8/2016)
u0003_0000303   -- update parent ID from 43162 to 150789  (5/4-5/5/2016)
u0001_2011004  -- update parent ID from 19672  to 150787 (5/18/2016)
u0003_0002508  -- CORRECT  - uploaded 5/5/2016
u0003_0002003  -- update parent ID from 131404 to 150798
p0003_0000480  -- no EAD.  Collection xml at 150812; update parent ID from
139834 to 150812 (2/2/2016)
u0003_0000863  -- update parent ID from 73513 to 150796 (2/12-4/11/2016)
u0001_2008026   --update parent ID from 141366 to 150786  (3/7/2016)

Only u0003_0002508 had a correct parent ID for the digitized items.
Somehow it's assigning parent ids that don't have database entries.

**Comment by jlderidder** [comment]
I should add that the problem does NOT appear to be happening for assigning
parent_id values for pages of items.  Nor does updating the EAD have an
impact, to my relief.  Also, nothing from before February was impacted, so
likely there were changes in the code either over Christmas break or in
January that caused the issue.

**Comment by jlderidder** [comment]
in acumen/indexer/MetadataIndexer.java:
oldMeta.getParentId()  in buildNewMetadata() -- where is this function??
should it be uppercased?
i find getParentID, but not getParentId functions...

**Comment by jlderidder** [comment]
Correction... older content has been impacted also.  Items exist without assets, because their assets do not have a correct id for the MODS in the asset table.  And, as you heard via slack, in the end, everything had found = 0.

**Comment by jlderidder** [comment]
Database calls were not correctly configured. Mysql.java was calling localhost.
