### ISSUE TITLE
Full indexer hangs

### ISSUE THREAD

**Issue by jlderidder** [AcumenProject/acumen-indexer#2]
Tried running "acumen index all" on the 20th, and it just hung -- after checking on it after several hours, it was sleeping.  The incremental index that runs at 7 pm each night seems to be fine, and doesn't wipe out the changes we made to the database.  

Could this be the issue?
in /home/acumen/indexer/src/edu/ua/lib/acumen/database/Mysql.java, this line:

protected static String url = "jdbc:mysql://localhost:3306/"+Config.CURRENT_DB+"?useUnicode=yes&characterEncoding=UTF-8";

Does not reference the new hostname for the databases.  Shouldn't it call a config file to get the host?

**Comment by 8bitsquid** [comment]
That's probably just an old copy of the indexer source that wasn't removed after I put it in Git. The current source does expect the database host to be defined via the config file (as you mentioned). Looks like I forgot to include a copy of the config template with this repo, since everything will eventually use the same config from the main `acumen` repo.

If you were running the JAR from this repo separately, where there was no `config.xml`, that's likely why it was hanging. I suppose there's not the proper try/catch methods to stop the indexer when attempting to reference config values that don't exist.

I wasn't able to get everything properly organized/linked before my final hours at the UA Lib (even though I finally left at 9pm that day). Refer to the email I sent about a week ago that outlines what loose ends were left hanging (to be tidied up after the contract work agreement gets finalized and I can get back into your servers).
